Repository SyndemicsLab/hep-ce, pull requests merged in 2025-07, with the labels that each got.

#117 Hotfix: Treatment Limit
  src/event/internals/treatment_internals.hpp
Labels: bug

#121 [Documentation] Documentation Revision
  Doxyfile
  LICENSE.txt
  README.md
  docs/src/custom.css
  docs/src/data.md
  docs/src/differences.md
  docs/src/events.md
  docs/src/faq.md
  docs/src/header.html
  docs/src/index.md
  docs/src/installation.md
  docs/src/limitations.md
  docs/src/run.md
  extras/examples/sim.conf
  include/hepce/data/types.hpp
  include/hepce/model/simulation.hpp
  src/data/types.cpp
Labels: documentation

#123 Hotfix/is eligible last time active bugs
  src/event/internals/treatment_internals.hpp
  src/model/internals/person_internals.hpp
  src/model/person.cpp
  tests/constants/config.hpp
  tests/src/event/hcv/treatment_test.cpp
Labels: bug

#129 [Bugfix] Address bugs from validation
  extras/examples/sim.conf
  extras/executable/exec.cpp
  include/hepce/data/writer.hpp
  src/data/internals/writer_internals.hpp
  src/data/writer.cpp
  src/event/fibrosis/internals/progression_internals.hpp
  src/event/fibrosis/progression.cpp
  src/event/internals/screening_internals.hpp
  tests/src/event/fibrosis/progression_test.cpp
Labels: bug

#132 Feature/track false negatives
  include/hepce/data/types.hpp
  include/hepce/model/person.hpp
  src/data/writer.cpp
  src/event/internals/screening_internals.hpp
  src/model/internals/person_internals.hpp
  src/model/person.cpp
  tests/mocks/person_mock.hpp
  tests/src/event/hcv/screening_test.cpp
  tests/src/model/person_test.cpp
Labels: enhancement
